name: VerifyIssue

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
  check_run:

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    name: PR has a linked issue.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Linked Issue
        uses: ./ 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
          _nnnn_                      
          dGGGGMMb     ,"""""""""""""""".
         @p~qp~~qMb    | Issue Missing! |
         M|@||@) M|   _;................'
         @,----.JM| -'
        JS^\__/  qKL
       dZP        qKRb
      dZP          qKKb
     fZP            SMMb
     HZM            MMMM
     FqM            MMMM
   __| ".        |\dS"qML
   |    `.       | `' \Zq
  _)      \.___.,|     .'
  \____   )MMMMMM|   .'
       `-'       `--' hjm
      

    